//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVS_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C102575814Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C102575814Owner()
        {
            this.C102575814Pet = new HashSet<C102575814Pet>();
        }
    
        public int OwnerID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public int Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C102575814Pet> C102575814Pet { get; set; }
    }
}
