//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVS_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADEntities : DbContext
    {
        public DADEntities()
            : base("name=DADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C102575814Owner> C102575814Owner { get; set; }
        public virtual DbSet<C102575814Pet> C102575814Pet { get; set; }
        public virtual DbSet<C102575814Procedure> C102575814Procedure { get; set; }
        public virtual DbSet<C102575814Treatment> C102575814Treatment { get; set; }
    }
}
